config/routes.rb
Rails.application.routes.draw do
  root "surveys#index"
  resources :surveys
  devise_for :users
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  # belongs_to :question
  has_many :answered_questions
end

app/models/answered_question.rb
class AnsweredQuestion < ActiveRecord::Base
  belongs_to :response
  belongs_to :answer
  belongs_to :question
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :survey
  has_many :answers
  has_many :answered_questions
end

app/models/response.rb
class Response < ActiveRecord::Base
  belongs_to :user
  belongs_to :survey
  has_many :answered_questions
end

app/models/survey.rb
class Survey < ActiveRecord::Base
  belongs_to :user
  has_many :questions
  has_many :responses
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable
         # :omniauthable, omniauth_providers: [:facebook]
         #:lockable, :timeoutable

  has_many :surveys
  has_many :responses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  def index
    @surveys = Survey.all
  end

  def show
    @survey = Survey.find(params[:id])
    # p "$"*99
    # p @survey
    # redirect_to root_path
  end

  def new
    @survey = Survey.new

  end

  def create
    survey = Survey.new(title: params[:survey][:title], user_id: current_user.id)
    if survey.save
      redirect_to edit_survey(survey)
    else
      flash[:notice] = 'Something went wrong'
      redirect_to root_path
    end
  end

  def edit
    survey = Survey.find(params[:id])
    p "#"*99
    p params

  end

  def update

  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  def new
    super
  end

  # POST /resource/confirmation
  def create
    super
  end

  # GET /resource/confirmation?confirmation_token=abcdef
  def show
    super
  end

  protected

  # The path used after resending confirmation instructions.
  def after_resending_confirmation_instructions_path_for(resource_name)
    super(resource_name)
  end

  # The path used after confirmation.
  def after_confirmation_path_for(resource_name, resource)
    super(resource_name, resource)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  def new
    super
  end

  # POST /resource/password
  def create
    super
  end

  # GET /resource/password/edit?reset_password_token=abcdef
  def edit
    super
  end

  # PUT /resource/password
  def update
    super
  end

  protected

  def after_resetting_password_path_for(resource)
    super(resource)
  end

  # The path used after sending reset password instructions
  def after_sending_reset_password_instructions_path_for(resource_name)
    super(resource_name)
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    p "@"*99
    p params
    super
    p "#"*99
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  def cancel
    super
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.for(:sign_up) << :attribute
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.for(:account_update) << :attribute
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    super(resource)
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    super(resource)
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.for(:sign_in) << :attribute
  end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  def new
    super
  end

  # POST /resource/unlock
  def create
    super
  end

  # GET /resource/unlock?unlock_token=abcdef
  def show
    super
  end

  protected

  # The path used after sending unlock password instructions
  def after_sending_unlock_instructions_path_for(resource)
    super(resource)
  end

  # The path used after unlocking the resource
  def after_unlock_path_for(resource)
    super(resource)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def logged_in?
    !!current_user
  end
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyDeviseRun</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<header>
<% if logged_in? %>
    Hello <%= current_user.first_name %>
    <img src="<%= current_user.image %>">
    <%= button_to 'Log out', destroy_user_session_path, method: 'delete' %>
  <% else %>
    Welcome, please log in or register
    <%= button_to 'Register', new_user_registration_path, method: 'get' %>
    <%= button_to 'Log in', new_user_session_path, method: 'get' %>
  <% end %>

</header>

<%= yield %>

</body>
</html>

app/views/surveys/edit.html.erb
<h3><%= flash[:notice] %></h3>

<h1>Surveys#edit</h1>
<h3>Add questions:</h3>

app/views/surveys/index.html.erb
<h3><%= flash[:notice] %></h3>
<% if logged_in? %>
  <h1>This are the surveys you have taken <%= current_user.first_name %></h1>
  <%= link_to "Create new survey", new_survey_path %>
  <% current_user.responses.each do |r| %>
    <h3>Survey title: <%= r.survey.title %></h3>
    <table>
      <tr>
        <th>Num</th><th>Question</th><th>Answer</th>
      </tr>
    <% r.answered_questions.each_with_index do |aq,i| %>
      <tr>
        <td><%= (i+1).to_s %></td>
        <td><%= aq.question.question %>?</td>
        <td><%= aq.answer.answer %></td>
      </tr>
    <% end %>
    </table>
  <% end %>
<% else %>

  <h1>This are all of our surveys</h1>
  <h3>Pick one...</h3>
  <table>
    <tr>
      <th>Title</th>
    </tr>
    <% @surveys.each do |s| %>
    <tr>
      <td><%= link_to s.title, survey_path(s) %></td>
    </tr>
    <% end %>
  </table>
<% end %>

app/views/surveys/new.html.erb
<h3><%= flash[:notice] %></h3>

<h1>Surveys#new</h1>
  <%= form_for @survey do |f|%>
    <%= f.label 'Survey title' %>
    <%= f.text_field :title %><br>
    <br>
    <%= f.submit "Next" %>
  <% end %>
  <br>
<%= link_to "Back", root_path %>

app/views/surveys/show.html.erb
<h1>Survey</h1>
<h3>Title: <%= @survey.title %></h3>
<table>
  <tr>
    <th>Num</th><th>Question</th>
  </tr>
    <% @survey.questions.each_with_index do |q,i| %>
      <tr>
        <td><%= (i+1).to_s %></td>
        <td><%= q.question %>?</td>
      </tr>
    <% end %>
</table>
<%= link_to "Back", root_path %>